import { Configuration } from './types';

export default (config: Configuration) => {
    if (!config.config.jsApiList) {
        config.config.jsApiList = [
            'onMenuShareAppMessage',
            'onMenuShareWechat',
            'onMenuShareTimeline',
            'startRecord',
            'stopRecord',
            'onVoiceRecordEnd',
            'playVoice',
            'pauseVoice',
            'stopVoice',
            'onVoicePlayEnd',
            'uploadVoice',
            'downloadVoice',
            'chooseImage',
            'previewImage',
            'uploadImage',
            'downloadImage',
            'getLocalImgData',
            'previewFile',
            'getNetworkType',
            'onNetworkStatusChange',
            'openLocation',
            'getLocation',
            'startAutoLBS',
            'stopAutoLBS',
            'onLocationChange',
            'onHistoryBack',
            'hideOptionMenu',
            'showOptionMenu',
            'hideMenuItems',
            'showMenuItems',
            'hideAllNonBaseMenuItem',
            'showAllNonBaseMenuItem',
            'closeWindow',
            'openDefaultBrowser',
            'scanQRCode',
            'selectEnterpriseContact',
            'openEnterpriseChat',
            'chooseInvoice',
            'selectExternalContact',
            'getCurExternalContact',
            'openUserProfile',
            'shareAppMessage',
            'shareWechatMessage',
            'startWifi',
            'stopWifi',
            'connectWifi',
            'getWifiList',
            'onGetWifiList',
            'onWifiConnected',
            'getConnectedWifi',
            'setClipboardData',
            'getClipboardData',
        ];
    }
    return config;
};
